#!/usr/bin/env python3
"""Turns research/help/*.json into src/HelpText.cpp.

One JSON file per maker, written by hand from that maker's own manual; this flattens the lot
into a table the plugin can carry. Never edit HelpText.cpp — edit the JSON and run this.

    python3 research/make_help.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
HELP = os.path.join(HERE, 'help')
OUT = os.path.join(os.path.dirname(HERE), 'src', 'HelpText.cpp')


def cstr(s):
    out = []
    for ch in s:
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        elif ch == '\n':
            out.append('\\n')
        else:
            out.append(ch)
    return '"' + ''.join(out) + '"'


def tags_of(entry):
    """A module's entry is a list of lines, and optionally a "tags" object beside it saying which
    line covers which jack or knob. Accepts either:

        "Model": ["line", "line"]
        "Model": {"lines": [...], "in": {"0": 2, "1": 3}, "out": {...}, "param": {...}}

    A tag map is port index -> line index. Anything not mentioned is -1, meaning nothing here
    describes that control."""
    if isinstance(entry, dict):
        lines = entry.get('lines', [])
        maps = (entry.get('in', {}), entry.get('out', {}), entry.get('param', {}))
    else:
        lines = entry
        maps = ({}, {}, {})
    if isinstance(lines, str):
        lines = [lines]
    out = []
    for m in maps:
        if not m:
            out.append([])
            continue
        highest = max(int(k) for k in m)
        table = [-1] * (highest + 1)
        for k, v in m.items():
            if not (0 <= int(v) < len(lines)):
                raise ValueError('tag points at line %s, which does not exist' % v)
            table[int(k)] = int(v)
        out.append(table)
    return lines, out


def main():
    entries = []          # (plugin, model, [lines], [in, out, param])
    sources = []          # (plugin, url, count)
    for name in sorted(os.listdir(HELP)):
        if not name.endswith('.json'):
            continue
        with open(os.path.join(HELP, name)) as f:
            doc = json.load(f)
        plugin = doc['plugin']
        mods = doc['modules']
        for model, entry in sorted(mods.items()):
            lines, tables = tags_of(entry)
            entries.append((plugin, model, lines, tables))
        sources.append((plugin, doc.get('source', ''), len(mods)))

    entries.sort()

    with open(OUT, 'w') as f:
        f.write('/** GENERATED by research/make_help.py — do not edit.\n\n')
        f.write('What each module is, in point form, written from its maker\'s own manual.\n')
        f.write('See Help.hpp for what this is for and where the wording rules come from.\n\n')
        f.write('Sources:\n')
        for plugin, url, count in sources:
            f.write('  %-24s %4d modules  %s\n' % (plugin, count, url))
        f.write('*/\n#include "Help.hpp"\n\n#include <cstddef>\n\n')

        for i, (plugin, model, lines, tables) in enumerate(entries):
            f.write('static const char* const L%d[] = {\n' % i)
            for line in lines:
                f.write('\t%s,\n' % cstr(line))
            f.write('};\n')
            for kind, table in zip(('I', 'O', 'P'), tables):
                if table:
                    f.write('static const short %s%d[] = {%s};\n'
                            % (kind, i, ','.join(str(x) for x in table)))
        f.write('\n/** Sorted by plugin then model, so it can be searched rather than walked. */\n')
        f.write('const HelpEntry HELP[] = {\n')
        for i, (plugin, model, lines, tables) in enumerate(entries):
            cells = []
            for kind, table in zip(('I', 'O', 'P'), tables):
                cells.append('%s%d, %d' % (kind, i, len(table)) if table else 'NULL, 0')
            f.write('\t{%s, %s, L%d, %d, %s},\n'
                    % (cstr(plugin), cstr(model), i, len(lines), ', '.join(cells)))
        f.write('};\n')
        f.write('const int HELP_COUNT = %d;\n' % len(entries))

    tagged = sum(1 for e in entries if any(e[3]))
    print('%d modules across %d makers, %d with controls tagged -> %s'
          % (len(entries), len(sources), tagged, OUT))
    return 0


if __name__ == '__main__':
    sys.exit(main())
