/** GENERATED by research/make_help.py — do not edit.

What each module is, in point form, written from its maker's own manual.
See Help.hpp for what this is for and where the wording rules come from.

Sources:
  Bogaudio                  111 modules  https://github.com/bogaudio/BogaudioModules/blob/master/README.md
  NYSTHI                      2 modules  No maker manual. Read from the panels, the port map we hand-read, the community manual at https://github.com/patman023/nysthimanual and its changelog.
*/
#include "Help.hpp"

#include <cstddef>

static const char* const L0[] = {
	"Attack/decay envelope generator, 3HP",
	"Both stages run to 10 seconds, each with a 0-10V CV attenuated by its knob",
	"A trigger or gate starts the cycle; EOC — a pulse at the end of it",
	"A new trigger during the decay re-enters the attack from the current level",
	"Runs continuously, with no trigger needed",
	"Straight segments instead of curved",
};
static const char* const L1[] = {
	"ADSR envelope generator, 3HP",
	"Attack, decay and release run to 10 seconds, exponentially scaled",
	"0 to 10 volts, linear",
	"Drives it; lights under the knobs show the active stage",
	"Straight segments instead of curved",
};
static const char* const L2[] = {
	"Ring and amplitude modulator with a variable rectifier; expects 5V signals",
	"MOD and CAR are multiplied to OUT",
	"Folds the negative half of MOD positive before that multiplication; bipolar CV at RECT",
	"MOD after the rectifier",
	"Mixes the result against the unmodulated carrier; bipolar CV at D/W",
};
static const char* const L3[] = {
	"Envelope generator — AR when triggered, ASR when gated",
	"Each with a CV attenuated by its knob",
	"Sustain level",
	"Straight segments instead of curved",
};
static const char* const L4[] = {
	"Additive oscillator — up to 100 sine partials summed",
	"How many",
	"Their spacing in frequency; O-SKEW and E-SKEW push the odd and even ones off it",
	"Tilts their amplitudes; BALANCE cuts the odd or the even ones",
	"Shapes them like a low-pass or high-pass",
	"All of these take CV; V/OCT sets the pitch",
};
static const char* const L5[] = {
	"Eight-step sequencer — one knob per step, the step chosen by a clock, by a voltage, or by both together",
	"Advances the step",
	"The sequence length",
	"The direction, forward or reverse",
	"Knob and CV address a step directly",
	"Output range on the menu; 10V either way by default",
	"Takes ASX expanders, eight steps each",
};
static const char* const L6[] = {
	"Chainable expander for ADDR-SEQ — eight more steps",
	"The base module's STEPS and SELECT then work across the whole chain",
	"Goes immediately to the right of the ADDR-SEQ, or of the previous ASX",
};
static const char* const L7[] = {
	"Spectrum analyser, four channels, plotted on one display",
	"Each input passed through unchanged",
	"Scrolls the frequency span shown",
	"Averages frames to steady the plot, at the cost of lag",
	"The FFT size, traded against CPU",
	"The window function applied before the FFT",
	"Click and hold the display to freeze it and read each channel's level at the frequency under the pointer",
};
static const char* const L8[] = {
	"Spectrum analyser, eight channels, 42HP, almost all display",
	"Works as ANALYZER does, with range, smoothing, quality and window on the menu",
	"One FFT size larger than ANALYZER offers",
	"Clicking the display freezes it, so drag near the left edge to move the module",
};
static const char* const L9[] = {
	"Arpeggiator fed from polyphonic pitch and gate — patch it straight to Rack's MIDI-CV",
	"A gate going high on a channel of GATE adds the pitch on that channel of V/OCT to the arpeggio",
	"One note per pulse; required, or nothing happens",
	"Up, down, pendulum, pendulum repeat, in order, random, shuffle",
	"Output gate length, as a proportion of the clock period",
	"Latches the arpeggio so it keeps playing after every input gate has fallen",
	"Restarts playback on the next clock",
	"The outputs are monophonic. Patch into ASSIGN to play them through a polyphonic voice",
};
static const char* const L10[] = {
	"Assigns notes to the channels of a polyphonic voice — so envelope tails can ring out",
	"Each gate at GATE hands the pitch at V/OCT to a poly channel, with a matching gate on the same channel",
	"How many channels to cycle through; the oldest is reused when they run out",
	"Next assignment back to channel 1",
	"With a polyphonic input it reassigns instead, so the in and out channel counts can differ",
};
static const char* const L11[] = {
	"Blank panel, 3HP",
	"No ports, no controls",
};
static const char* const L12[] = {
	"Blank panel, 6HP",
	"No ports, no controls",
};
static const char* const L13[] = {
	"Boolean logic",
	"The upper section takes two inputs and outputs their AND, OR and XOR",
	"The negation of its own input",
	"Above 1V counts as true; a true output is 5V",
};
static const char* const L14[] = {
	"Delay meant for CV, though it works on audio — delay a trigger, double an envelope, correct latency",
	"The delay in seconds, scaled by the range knob to 0.1, 1 or 10 seconds; CV 0-10V",
	"Mixes the delayed signal against the original; CV bipolar",
};
static const char* const L15[] = {
	"Swept-sine generator",
	"The ends of the sweep; V/O1 and V/O2 are 1V/octave inputs added to them",
	"How long the sweep takes; CV 0-10V",
	"Exponential sweep instead of linear",
	"Starts one sweep; LOOP repeats them",
	"Pulse when a sweep ends",
};
static const char* const L16[] = {
	"Hard clipper and distortion, 6HP, stereo",
	"It chops the signal at the voltage matching the threshold, which distorts it heavily. LMTR does the same job by reducing the level instead, and distorts far less",
	"The level it clips at, in decibels; 0dB is the output of a standard oscillator. CV alongside",
	"Amplifies after the clipping; CV alongside",
	"A softer or harder transition as the signal crosses the threshold",
	"The inputs; unpatched R is fed from L",
};
static const char* const L17[] = {
	"Window comparator",
	"Each normalled to 0V and summed with its own offset knob",
	"A greater or equal, A less than, the two within the window, and the negation of that",
	"How close counts as equal; CV 0-10V",
	"Delays any change of output by up to a second; CV 0-10V",
	"High and low are 0V and 10V, or 5V either way",
};
static const char* const L18[] = {
	"Distortion built on a window comparator; meant for audio rates",
	"Scaled by their knobs and bipolar CVs. B unpatched is normalled to +5V",
	"How far apart A and B must be to count as unequal; CV 0-10V",
	"Follow the comparison as 5V",
	"Those three through attenuverters, blended against a dry mix of A and B by DRY/WET",
	"For a window comparator to use on CV, use CMP instead",
};
static const char* const L19[] = {
	"ADSR envelope generator with a delay stage before the attack, and a self-gating hold mode",
	"GATE, where TRIGGER gates it as usual; or TRIG, where a trigger starts a cycle held open for the time set by HOLD",
	"Loops it, in TRIG mode",
	"The envelope, 0-10V",
	"The inverse of the envelope",
	"A trigger when the release finishes",
	"Attack, decay and release are each switchable between linear, exponential and logarithmic",
	"Times ten times slower; RETRIG — attack from the current level, or restart from the delay",
};
static const char* const L20[] = {
	"DADSRH with a CV input for every knob",
	"Plus a gate output per stage, high for the duration of that stage",
};
static const char* const L21[] = {
	"Trigger-to-gate converter",
	"Starts an optional delay of up to 10 seconds, then a gate of up to 10 seconds",
	"A trigger when the cycle finishes",
	"LOOP, or holding TRIG high, repeats the cycle",
};
static const char* const L22[] = {
	"Pitch CV processor for a detuned pair of oscillators",
	"The pitch at V/OCT is raised at OUT+ and lowered at OUT- by the number of cents set by the knob and its CV",
	"The pitch unchanged",
};
static const char* const L23[] = {
	"Three-band equalizer, fixed frequencies — LOW 100Hz, MID 350Hz, HIGH 1000Hz",
	"Each knob sets its band's gain, -36dB through unity to +12dB",
	"IN to OUT; no CV",
};
static const char* const L24[] = {
	"Three-band equalizer in stereo — LOW 100Hz, MID 350Hz, HIGH 1000Hz",
	"Left and right are filtered separately, by one shared set of three knobs",
	"No CV",
};
static const char* const L25[] = {
	"Edge detector, comparator and trigger-to-gate utility",
	"The input crossing above this puts the module high and raises the HIGH output",
	"Crossing below this drops it",
	"Minimum time in the high state; stops jitter on fast inputs",
	"1ms triggers on those transitions",
};
static const char* const L26[] = {
	"Low-frequency oscillator — one wave shape at eight phases, 45 degrees apart",
	"Chosen by the selector; all eight outputs carry the same shape",
	"Calibrated in volts; V/OCT is added to it",
	"Lower range",
	"Pulse width on the square, sampling on the rest, whichever the selected wave calls for. CV alongside",
	"Smoothing, applied last of all",
	"An offset added to the outputs; SCL scales them first. A CV each",
	"The phase of that output, in degrees from the fundamental, with a CV alongside",
	"The wave at the phase set by its own PHS knob",
	"Hard sync",
};
static const char* const L27[] = {
	"Router, one of eight in to one out — selected by clock, by voltage, or both",
	"A trigger advances the selection",
	"Back to the first input",
	"How many inputs to cycle through",
	"The direction, forward or reverse",
	"Knob and CV address an input directly, added to the clocked position. The CV runs -10V to +10V in steps of 1.25V",
};
static const char* const L28[] = {
	"Fixed filter bank — twelve band-pass filters with a low-pass and a high-pass on the ends, at the band frequencies of the Moog 914",
	"One knob per band, attenuating that band before they are mixed back together",
	"Shifts every band an octave either way; FCV is bipolar, attenuverted by the knob",
	"ALL, and separate mixes of the ODD and EVEN bands",
};
static const char* const L29[] = {
	"Sine oscillator and simple voice — several patched together make the classic FM algorithms",
	"Frequency knob is a ratio of the pitch at V/OCT, so one pitch CV drives a stack of operators at set intervals",
	"FM amount, with a CV",
	"Self-modulation of the sine, with a CV",
	"Output level, with a CV",
	"Fires the onboard ADSR, which can be routed to level, feedback or depth",
};
static const char* const L30[] = {
	"Two independent flip-flops",
	"Flips that channel between states A and B",
	"Whichever is selected outputs 5V, the other 0V",
	"Back to A",
};
static const char* const L31[] = {
	"Envelope follower — a CV tracking the amplitude at IN",
	"Slows and smooths the response; CV 0-10V",
	"Cuts to -36dB or lifts to +12dB; CV bipolar",
};
static const char* const L32[] = {
	"Quadrature low-frequency oscillator — one wave shape at four phases, 0, 90, 180 and 270 degrees",
	"Selects the wave; all four outputs carry the same shape",
	"Calibrated in volts; 0V is 2.04Hz. V/OCT is added to it",
	"Four octaves lower again",
	"One knob doing two jobs, whichever the selected wave calls for: pulse width on the square, and sampling — stepping the output — on the rest. CV at S/PW",
	"Smoothing: a slew limiter applied last, after offset and scale",
	"An offset added to the outputs; SCL scales them before the offset is added. A CV each",
	"The phase of that output, in degrees from the fundamental, with a CV alongside",
	"The wave at the phase set by its own PHS knob",
	"Hard sync",
	"On the stepped random wave all four outputs draw from one sequence, so they differ in phase and not in value",
};
static const char* const L33[] = {
	"Four independent manual gates, a button and an output each",
	"An output sends +5V while its button is held, 0V otherwise",
	"The high voltage and the trigger-on-load option apply to all four",
};
static const char* const L34[] = {
	"Two independent inverters",
	"IN passes to OUT unchanged until the button is held or GATE goes high, and is inverted while it is",
	"A press or a trigger toggles the state instead of holding it",
};
static const char* const L35[] = {
	"Low-frequency oscillator — six waveforms out at once: ramp down, ramp up, triangle, stepped random, square and sine",
	"Calibrated in volts; 0V is C-3, 2.04Hz. V/OCT is added to it, seven octaves below a normal oscillator",
	"Four octaves lower again",
	"Samples the output into a step function; the more it is turned up, the coarser the steps. CV at SAM",
	"Pulse width of the square output. CV at PW",
	"Smoothing: a slew limiter applied last of all, after offset and scale. It rounds the square into a shark fin and turns the stepped random output into a random walk",
	"An offset added to the output, -5 to +5V, or 10 either way on the menu",
	"Scales the output, before the offset is added",
	"One CV input shared by offset and smoothing; which of the two it drives is set on the menu",
	"CV for scale",
	"Hard sync, and it picks a new value on the stepped random output",
};
static const char* const L36[] = {
	"Low-frequency oscillator, 3HP — one waveform at a time",
	"Rate; V/OCT is added to it",
	"Selected by the button; square is fixed at half, pulse defaults to a tenth and is set on the menu",
	"Lower range",
	"An offset added to the output; SCL scales it before the offset is added",
	"Hard sync",
	"Sampling and smoothing are on the menu rather than the panel",
};
static const char* const L37[] = {
	"Low-pass gate, compact — envelope, low-pass filter and VCA in one",
	"A rising edge fires the envelope",
	"Its length; one shape knob curves both the rise and the fall",
	"Envelope is applied in full to both the filter and the VCA",
	"No CV inputs",
};
static const char* const L38[] = {
	"Low-pass gate — envelope, low-pass filter and VCA in one",
	"A rising edge fires the envelope",
	"Its length and basic shape; CV at RESP, 0-10V",
	"The curves of the two segments",
	"IN runs through the filter then the VCA to OUT",
	"Each has a BIAS knob, a CV input, and an ENV attenuverter setting how much envelope it gets",
	"VCA linear in amplitude instead of decibels",
};
static const char* const L39[] = {
	"Filter, compact — low-pass, high-pass, band-pass or band-reject, switched",
	"Cutoff; CV input alongside it",
	"Resonance",
	"Slope is fixed, and set on the menu",
};
static const char* const L40[] = {
	"Oscillator, 3HP — one waveform at a time",
	"Sine, triangle, saw, square, or 25% or 10% pulse",
	"Pitch",
	"Modulates pitch; linear and through-zero on the menu",
};
static const char* const L41[] = {
	"SWITCH with two gate inputs and logic between them",
	"With one gate patched, or none, it behaves exactly as SWITCH",
	"With both patched, the routing follows the logic over the two gates",
	"OR, AND, XOR, NOR, NAND",
	"The mode can be set by a 0-5V CV, which overrides the button",
};
static const char* const L42[] = {
	"Limiter, 6HP, stereo",
	"It holds the signal below the threshold by reducing its level rather than chopping it, so it distorts far less than CLPR",
	"The level it works down to, in decibels; 0dB is the output of a standard oscillator. CV alongside",
	"Amplifies after the limiting; CV alongside",
	"A softer or harder transition as the signal crosses the threshold",
	"Attack and release times are on the menu",
};
static const char* const L43[] = {
	"Manual gate — all eight outputs send +5V while the TRIG button is held, 0V otherwise",
	"Menu — high voltage +10V instead; and a trigger pulse on patch load, the equivalent of a loadbang",
};
static const char* const L44[] = {
	"Router, one in and eight out — the input to each output through its own attenuverter",
	"Knobs default to zero, so nothing passes until some are turned up",
};
static const char* const L45[] = {
	"Matrix mixer, four by four — each input into each output mix through its own attenuverter",
	"Knobs default to zero, so nothing is heard until some are turned up",
	"Outputs soft-clip at 12V",
	"Menu — hard clipping, which sums CVs precisely; input gain down to -12dB; average instead of sum; unipolar knobs",
	"Takes the MX44CVM expander",
};
static const char* const L46[] = {
	"Expander for MATRIX44 — a bipolar CV input and a mute button per matrix point",
	"Each CV is attenuverted by its own knob",
	"A mute overrides both knob and CV; right-click one to solo that point",
	"Goes immediately to the right of its MATRIX44",
};
static const char* const L47[] = {
	"Matrix mixer, eight in and one out — each input into the mix through its own attenuverter",
	"Knobs default to zero, so nothing is heard until some are turned up",
	"Output soft-clips at 12V; hard clipping or none on the menu",
};
static const char* const L48[] = {
	"Matrix mixer, eight by eight — each input into each output mix through its own attenuverter",
	"Knobs default to zero, so nothing is heard until some are turned up",
	"Outputs soft-clip at 12V; hard clipping, averaging and unipolar knobs on the menu",
	"Takes the MX88CV and MX88M expanders",
};
static const char* const L49[] = {
	"Expander for MATRIX88 — a bipolar CV input per matrix point, each attenuverted by its own knob",
	"Goes immediately to the right of the MATRIX88, or of an MX88M already expanding one",
};
static const char* const L50[] = {
	"Expander for MATRIX88 — a mute button per matrix point",
	"A mute overrides the knob, and any CV from an MX88CV",
	"Right-click one to solo that point",
	"Goes immediately to the right of the MATRIX88, or of an MX88CV already expanding one",
};
static const char* const L51[] = {
	"Low-pass gate in stereo, with a high-pass filter added and CV over everything",
	"The envelope is the whole of VISH, fired by a rising edge at GATE",
	"Scales the envelope; 0V cuts it by 6dB, 10V leaves it alone. Meant for MIDI velocity",
	"Pans the envelope between the left and right channels; bipolar CV",
	"Left and right each run through a low-pass, a high-pass and a VCA",
	"Every section has a BIAS knob, a CV with attenuverter, and an ENV amount that also takes CV",
	"Filters in series instead of parallel",
};
static const char* const L52[] = {
	"Fader and VCA, 3HP, with a mute button",
	"IN to OUT under the fader",
	"Level and mute each take CV",
};
static const char* const L53[] = {
	"Fader and VCA in stereo, with a mute button — MIX1 in stereo",
	"L is normalled to R, so one cable feeds both",
	"Level and mute each take CV",
};
static const char* const L54[] = {
	"Four-channel mixer with panning, mutes and a master fader — MIX8 in four channels",
	"Channel and master levels take a 0-10V CV, attenuated by the fader",
	"The panners take a bipolar CV, attenuverted by the knob",
	"Outputs are stereo, and mono if only one is patched",
	"Right-click a mute to solo that channel",
};
static const char* const L55[] = {
	"Expander for MIX4 — a three-band EQ for each of its four channels, two sends, and two stereo returns",
	"The EQ for that channel, at 100Hz, 350Hz and 1000Hz",
	"That channel's level into each send, with a CV input each",
	"Takes the signal before the channel's fader, mute and EQ rather than after",
	"Stereo, right normalled to left, each with a level knob; A also has a level CV",
	"The returns are injected into the master stage of the MIX4",
	"Goes immediately to the right of its MIX4",
};
static const char* const L56[] = {
	"Eight-channel mixer with panning, mutes and a master fader; faders calibrated in decibels",
	"CV 0-10V, attenuated by the fader",
	"CV bipolar, attenuverted by the knob",
	"Outputs are stereo, and mono if only one is patched",
	"Right-click a mute to solo that channel",
	"Master has MUTE and DIM",
};
static const char* const L57[] = {
	"Expander for MIX8 — a three-band EQ per channel, two sends and two stereo returns",
	"A level knob and CV each",
	"Takes the signal before the channel's fader, mute and EQ rather than after",
	"Right normalled to left; injected into the master stage. Return A has a level CV",
	"Goes immediately to the right of its MIX8",
};
static const char* const L58[] = {
	"Sums the channels of a polyphonic input to one mono output — Rack's SUM with a compressor added",
	"How much compression, to even out the level as more or fewer channels sound. At zero it is exactly SUM",
	"Attenuates the output, which soft-clips at 12V",
};
static const char* const L59[] = {
	"Multiple, 3HP — two 1-to-3 splitters",
	"With nothing patched to the second section's input, it becomes one 1-to-6",
	"Polyphonic inputs are duplicated with their channels intact",
};
static const char* const L60[] = {
	"Unity mixer, eight inputs summed to one output, with a mute button on each",
	"Output limited to 12V, soft by default; hard clipping on the menu",
	"In averaging mode the divisor counts every connected input, muted or not",
};
static const char* const L61[] = {
	"Eight independent mutes",
	"Each channel passes IN to OUT unless its button is on or its CV input is positive",
	"Right-click a button to solo that channel",
	"Each channel is independently polyphonic",
	"Menu — CV inputs latch instead of holding",
};
static const char* const L62[] = {
	"Noise source — blue, white, pink, red and Gaussian, each at its own output, all at once",
	"Poly channel count for those outputs is set on the menu",
	"A separate circuit: a signal at IN comes out with its negative half folded positive, turning bipolar noise into unipolar CV",
};
static const char* const L63[] = {
	"Noise gate, 6HP, stereo — it attenuates whatever is quieter than the threshold",
	"The level below which it cuts, in decibels. CV alongside",
	"How completely the quiet part is cut. CV alongside",
	"A softer or harder transition as the signal crosses the threshold",
	"Attack and release times are on the menu",
};
static const char* const L64[] = {
	"Adds an offset to a signal and scales it",
	"Each with a 0-10V CV input",
	"Menu — scale then offset, the default; or offset then scale",
	"With nothing patched to IN the output is the offset on its own, so it doubles as a constant voltage source",
};
static const char* const L65[] = {
	"Router, one in to one of eight out — selected by clock, by voltage, or both",
	"A trigger advances the selection",
	"Back to the first output",
	"How many outputs to cycle through",
	"The direction, forward or reverse",
	"Knob and CV address an output directly, added to the clocked position",
};
static const char* const L66[] = {
	"Parametric equalizer, three bands",
	"Each band filters IN at its own FREQ and LEVEL; the three mix to OUT",
	"CV per band, 0-10V",
	"Frequency CV per band, summed with a global FCV that moves all three",
	"Bandwidth per band, with CV",
	"First band can be switched to low-pass, last to high-pass",
};
static const char* const L67[] = {
	"Parametric equalizer, fourteen bands — controlled as PEQ6 is",
	"A direct output per band, plus the mix at OUT",
	"Mixes of the odd- and even-numbered bands",
};
static const char* const L68[] = {
	"Expander for PEQ14 — an envelope follower output per band",
	"How fast the followers respond; CV 0-10V",
	"Cuts or boosts them; CV bipolar",
	"Goes immediately to the right of its PEQ14",
};
static const char* const L69[] = {
	"Parametric equalizer, six bands",
	"Each band filters the signal at IN at its own frequency and level, and the six are mixed to OUT",
	"One per band, its centre frequency; that band's FCV input is attenuverted by its own knob",
	"One per band, how much of it reaches the mix; a CV input each",
	"A global FCV input with its own knob moves every band's frequency at once",
	"One bandwidth for all six bands, with a CV",
	"Whether the frequency CVs cover an octave or the full range",
	"Band 1 can be switched from band-pass to low-pass, and band 6 to high-pass",
	"Each band also has a direct output of its own",
	"Menu — a band whose direct output is patched can be left out of the main mix",
};
static const char* const L70[] = {
	"Expander for PEQ6 — an envelope follower output per band",
	"How fast the followers respond",
	"Cuts or boosts them",
	"Goes immediately to the right of its PEQ6",
};
static const char* const L71[] = {
	"Two independent stereo panners",
	"Each position takes a bipolar CV, attenuverted by its knob",
	"Outputs soft-clip at 12V",
};
static const char* const L72[] = {
	"Four-step programmer — knobs A, B, C and D per step, going to the four outputs when that step is current",
	"A step is selected by its button, by a trigger at its own SELECT input, or by the CLOCK and global SELECT inputs, with S.O.C. deciding whether SELECT is read continuously or only on a clock",
	"A trigger whenever the step changes",
	"A trigger when that step is selected",
	"Output range on the menu",
	"Takes PGMRX expanders, four steps each",
};
static const char* const L73[] = {
	"Chainable expander for PGMR — four more steps",
	"Each step has its own A, B, C and D knobs, select button, select input and trigger output",
	"Goes immediately to the right of the PGMR, or of the previous PGMRX",
};
static const char* const L74[] = {
	"A fixed voltage to each of up to sixteen channels of a polyphonic output, one knob per channel",
	"For putting deliberate variation across the channels of a poly voice",
	"The channel count; a cable at the CHAN input takes the count from that instead",
	"Voltage range on the menu",
};
static const char* const L75[] = {
	"A fixed voltage to each of up to eight channels of a polyphonic output, one knob per channel",
	"For putting deliberate variation across the channels of a poly voice",
	"Channel count and voltage range are both on the menu",
};
static const char* const L76[] = {
	"Turns a monophonic signal into a polyphonic one, copying the input voltage to every channel",
	"The channel count",
	"A poly cable sets the count from its own channels; a mono one acts as a 0-10V CV selecting it",
	"All the OUT jacks are identical",
	"To copy an already-polyphonic signal, use MULT instead",
};
static const char* const L77[] = {
	"Offsets and scales each of up to sixteen channels of a polyphonic signal, a knob pair per channel",
	"With a cable at IN it processes that signal's channels and takes its channel count",
	"With none, CHAN sets the count and it merges the per-channel inputs and knob voltages into a poly output — a replacement for Rack's MERGE",
	"Each channel's offset has its own CV input, bipolar and attenuverted",
	"Menu — offset range, and whether scale or offset is applied first",
};
static const char* const L78[] = {
	"Offsets and scales each of up to eight channels of a polyphonic signal, a knob pair per channel",
	"With a cable at IN it processes that signal's channels",
	"With none, it merges the per-channel inputs and knob voltages into a poly output — a replacement for Rack's MERGE",
	"Each channel's offset has its own CV input",
};
static const char* const L79[] = {
	"Stereo compressor and noise gate with a sidechain",
	"Compress, or gate",
	"THRESHOLD, RATIO, ATTACK, DECAY — each with its own CV input",
	"Each with a bipolar CV added to the knob",
	"Sidechain input; IN/SIDE crossfades the detector between the main signal and it",
	"The detector's control signal, sent out",
	"RMS averages the input over a short window, PEAK reads its instantaneous level",
	"A softer or harder transition as the signal crosses the threshold",
};
static const char* const L80[] = {
	"Oscillator, 3HP — square and pulse only, built around pulse-width modulation",
	"Pitch",
	"Has its own attenuverter, and is summed with the PW knob rather than replacing it",
};
static const char* const L81[] = {
	"Gate generator whose gate length is a fraction of the clock period; also a clock divider and multiplier",
	"The incoming clock, measured pulse to pulse",
	"Gate length as a proportion of that period, from 1ms to the whole of it; CV at LEN",
	"How many clock pulses the period spans; CV at DIV",
	"How many gates are emitted within it; CV at MUL",
	"Clears the measured period and the divider count",
};
static const char* const L82[] = {
	"Frequency-response analyser — mainly useful to developers",
	"A swept sine out to the module under test; RETURN — its output back",
	"Plots both spectra and the difference between them",
	"The ends of the sweep",
	"Exponential sweep instead of linear",
	"Runs one cycle",
	"Runs cycles continuously",
	"A pulse when a cycle starts, and another at EOC when it ends",
	"Patching here replaces the internal sweep",
	"Aligns the response for modules that add sample delay",
};
static const char* const L83[] = {
	"Reference-tone generator and tuner",
	"A chromatic note",
	"Trims it by a semitone either way",
	"Display shows the note, the cents and the frequency",
	"The note as a 1V/octave CV, and as a pure sine tone",
};
static const char* const L84[] = {
	"Two sample-and-hold channels, each also able to track and hold",
	"A rising edge samples IN to OUT; the button does the same",
	"Output follows the input while the gate is high, and holds when it drops",
	"IN unpatched is normalled to an internal noise source; the lower GATE is normalled to the upper one",
	"Inverts that channel's output",
};
static const char* const L85[] = {
	"Envelope generator and VCA, after the EMS VCS3",
	"Stages are attack, on, decay and off — a trapezoid, not an ADSR. Each runs from near zero to 10 seconds",
	"Starts a cycle",
	"A trigger when the cycle finishes",
	"Loops the envelope, restarting it as the off stage ends",
	"The envelope, 0-10V, attenuated by the ENV knob; INV — its inverse",
	"IN runs through the internal VCA to OUT, under the envelope and the SIGNAL knob",
	"Times ten times longer",
};
static const char* const L86[] = {
	"SHAPER with a CV input for every knob",
	"Plus a gate output per stage, high for the duration of that stage",
};
static const char* const L87[] = {
	"Oscillator, 3HP, aimed at drum synthesis — sine by default, other shapes on the menu",
	"Pitch",
	"Modulates pitch",
	"Where in the cycle the wave restarts when SYNC fires; shapes the transient. Knob attenuverts the CV",
	"Hard sync",
};
static const char* const L88[] = {
	"Slew limiter — when the input changes quickly, the output follows more slowly",
	"The times, set independently, each calibrated as the time to catch up with a 10V change. CV 0-10V each",
	"A second pair of knobs curves the two segments, between logarithmic, linear and exponential",
	"Both rates ten times slower",
};
static const char* const L89[] = {
	"Pitch CV transposer, for stacking oscillators",
	"An interval, added to the pitch at V/OCT and sent to OUT",
	"The pitch unchanged, so several can be chained to build a chord",
	"Bipolar, shifting the interval a semitone per tenth of a volt",
	"Quantises that CV to semitones",
};
static const char* const L90[] = {
	"Arithmetic",
	"The sum, difference, maximum and minimum of its two inputs. An unpatched input counts as 0V",
	"The negation of its own input",
	"Output capped at 12V unless that is disabled on the menu",
};
static const char* const L91[] = {
	"Signal router, two channels",
	"While the button is held or GATE is high, each channel's HIGH input goes to its OUT; otherwise its LOW input does",
	"A click or a trigger toggles the routing instead of holding it",
};
static const char* const L92[] = {
	"Matrix mixer, sixteen by sixteen, with switches instead of knobs — SWITCH44 at sixteen by sixteen",
	"A switch passes its input into that output mix at unity gain, or at a level typed on its right-click menu",
};
static const char* const L93[] = {
	"Router, one in and eight out, with switches — the input reaches an output only while its switch is on",
	"A switch passes at unity gain; right-click one and type any level from -100% to 100%",
	"Menu — exclusive switching, allowing only one output at a time",
};
static const char* const L94[] = {
	"Matrix mixer, four by four, with switches instead of knobs",
	"Every switch is off by default; a click passes that input into that output mix at unity gain",
	"Right-click a switch and type any level from -100% to 100%",
	"Menu — inverting on a second click; average instead of sum; exclusive switching by row or by column",
	"Switches slew slightly when they change, so they do not pop",
};
static const char* const L95[] = {
	"Mixer, eight in and one out, with switches instead of knobs — an input reaches the output only while its switch is on",
	"A switch passes at unity gain; right-click one and type any level from -100% to 100%",
	"Menu — exclusive switching, allowing only one input through at a time; inverting on a second click",
};
static const char* const L96[] = {
	"Matrix mixer, eight by eight, with switches instead of knobs — SWITCH44 at eight by eight",
	"A switch passes its input into that output mix at unity gain, or at a level typed on its right-click menu",
};
static const char* const L97[] = {
	"Unity mixer, 3HP — up to eight inputs summed to one output. Audio, or CV and triggers",
	"Output limited to 12V, soft by default",
	"Menu — hard clipping, which sums CVs precisely; input gain down to -12dB; average instead of sum",
};
static const char* const L98[] = {
	"Copies a monophonic pitch and gate out to several polyphonic channels, for unison playing",
	"How many channels",
	"Spreads them up to half a semitone apart, evenly either side of the input pitch; CV attenuated by the knob",
	"With an odd number of channels, one of them keeps the pitch exactly",
};
static const char* const L99[] = {
	"Two independent voltage-controlled attenuators — an attenuator can only reduce a signal",
	"Each level takes a 0-10V CV, attenuated by its knob",
	"Linear in amplitude, which suits processing CV; otherwise linear in decibels",
};
static const char* const L100[] = {
	"Voltage-controlled amplifier — adds up to 12dB of gain, which is four times the input amplitude",
	"Level takes a 0-10V CV, attenuated by the slider",
	"The slider handle lights with the output level",
	"Output soft-clips at 12V",
};
static const char* const L101[] = {
	"Filter — low-pass, high-pass, band-pass or band-reject, switched",
	"Cutoff, or centre frequency in the band modes",
	"Bipolar, attenuverted, added to the cutoff",
	"Read as a pitch; set the knob to 0Hz for accurate key tracking",
	"Exponential, attenuated by the FM knob",
	"Resonance in the pass modes, bandwidth in the band modes; CV 0-10V",
	"From 1 to 12 poles, continuously; CV at SLP",
};
static const char* const L102[] = {
	"Four-channel mixer, 10HP, summing to one mono output",
	"A knob and a 0-10V CV, the CV attenuated by the knob",
	"Linear in amplitude, which suits mixing CV; otherwise linear in decibels",
	"Output hard-clipped at 12V; can be disabled on the menu",
};
static const char* const L103[] = {
	"Oscillator with square, saw, triangle and sine running at once, each on its own output",
	"Sets the pitch, marked in volts; 0V gives C4 at 261.63Hz",
	"Trims the pitch up to a semitone either way",
	"Drops the whole pitch range by seven octaves, so the module runs as an LFO",
	"Frequency follows the pitch voltage at 1000Hz per volt rather than an octave per volt, and the oscillator stops at 0V",
	"Sets the pulse width of the square wave, with a 50% square at noon",
	"Sets how deeply the FM jack modulates the frequency",
	"The switch beside the FM knob picks exponential modulation or linear through-zero modulation",
	"Pitch at a volt per octave, added to the frequency knob; the channels patched here set the oscillator's polyphony",
	"A rising edge here hard-syncs the oscillator, restarting its cycle",
	"Modulates the width of the square wave",
	"Square, saw, triangle and sine, all from the same oscillator at the same pitch",
	"Menu — DC offset correction, on by default, keeps the square output centred as the pulse width changes; turn it off when using that output as CV",
};
static const short I103[] = {8,9,10,6};
static const short O103[] = {11,11,11,11};
static const short P103[] = {1,2,3,5,6,7,4};
static const char* const L104[] = {
	"Stereo level meter",
	"L and R are metered and passed through unchanged to the outputs",
	"With nothing patched to R, L is metered on both displays",
	"A polyphonic input is summed before its level is taken",
};
static const char* const L105[] = {
	"VCA with three CV inputs of different kinds",
	"The knob sets how far the VCA opens; a 0-10V CV here takes over, attenuated by the knob. Patch an envelope",
	"Bipolar, attenuverted, and scaled by whatever LEVEL is doing. Patch an LFO for tremolo",
	"0-10V, scaled by V. R. and inverted, so a low voltage cuts the output. Meant for the velocity output of MIDI-CV",
	"Linear in amplitude instead of decibels",
};
static const char* const L106[] = {
	"Envelope generator imitating the vactrol circuits in hardware low-pass gates — the envelope inside MEGAGATE and LPG",
	"Makes a 10V square envelope and slews it",
	"Fires it",
	"Its minimum length; CV at MIN, 0-10V",
	"Slew times, each with its own CV; and slew shapes, sharing the bipolar SHAPE input",
	"All three times ten times longer",
};
static const char* const L107[] = {
	"One channel of random-walk CV, 3HP — one channel of WALK2",
	"How far and fast the voltage wanders; OFFSET shifts it; SCALE attenuates it. Each with CV",
	"A trigger moves the output to a new random value",
	"Sample-and-hold and track-and-hold modes are on the menu",
};
static const char* const L108[] = {
	"Two channels of random-walk CV, drawn as an X/Y trace on the display",
	"How far and fast the voltage wanders; OFFSET shifts it; SCALE attenuates it. Each with CV",
	"A third CV, 0-10V, derived from the other two",
	"Jumps both channels to a new random value, or samples and holds them; set by the selector below it",
	"Clicking or dragging the display drives the outputs directly",
};
static const char* const L109[] = {
	"Oscillator — square, saw, triangle and sine running at once, each with its own output, and a mixer combining all four at MIX",
	"Pulse width of the square wave",
	"Saturation on the saw wave",
	"Steps the triangle wave, a sample-and-hold effect on it",
	"FM feedback on the sine wave",
	"The phase of that wave, shifting it within its own cycle before it enters the mix",
	"How much of that wave goes into the MIX output. The OUT jack for a wave always carries it at full level, whatever this is set to",
	"CV for the FM depth",
	"Sets the pitch, marked in volts, -3 to +6; 0V is C4 at 261.63Hz. V/OCT is added to it",
	"Trims by one semitone either way",
	"Depth of the signal patched to the FM input",
	"Exponential modulation, or linear through-zero",
	"Hard sync",
	"The whole range down seven octaves",
	"Square, saw, triangle and sine, each at full level whatever its MIX knob is set to",
	"Four oscillators summed can run hot, so the menu sets whether this output is scaled to 5V, saturated, hard clipped, or left alone",
};
static const short I109[] = {10,7,1,5,6,2,5,6,3,5,6,4,5,6,8,12};
static const short O109[] = {14,14,14,14,15};
static const short P109[] = {8,9,13,10,11,1,5,6,2,5,6,3,5,6,4,5,6};
static const char* const L110[] = {
	"Crossfader between inputs A and B — also a two-channel mixer, or a dry/wet control",
	"The balance; CV bipolar, attenuverted by the knob",
	"The fade curve: both channels silent at centre, a constant-level crossfade, or both at full level at centre",
	"Linear in amplitude, which suits processing CV",
};
static const char* const L111[] = {
	"Four tap delay modelled on the Buchla 277. Patching an output back into an input builds a feedback loop, which overloads as the input level rises",
	"The delayed signal at the full time set by TIME",
	"The delayed signal at half the time set by TIME",
	"The delayed signal at a third of the time set by TIME",
	"The delayed signal at a quarter of the time set by TIME",
	"One of the four inputs into the delay line",
	"An attenuverter, -1 to +1, setting the level of the input on that row",
	"A CV setting the level of the input on that row",
	"The delay time, from 5ms to 200ms, default 100ms",
	"Shifts the delay range to 50ms to 2000ms in the x 10 position",
	"A CV modulating the delay time",
	"How far the TIME CV moves the delay time, -0.5 to +0.5",
};
static const short I111[] = {5,5,5,5,7,7,7,7,10};
static const short O111[] = {4,3,2,1};
static const short P111[] = {6,6,6,6,8,11,9};
static const char* const L112[] = {
	"Programmer is a sixteen stage Serge style programmer. One stage is active at a time, and the four knob voltages of that stage appear at the four outputs.",
	"Sixteen stages, numbered 1 to 16",
	"One knob per stage in each row, setting the four voltages that stage holds.",
	"Carries the voltage set by the A knob of the active stage.",
	"Carries the voltage set by the B knob of the active stage.",
	"Carries the voltage set by the C knob of the active stage.",
	"Carries the voltage set by the D knob of the active stage.",
	"An input taking a voltage that picks which stage is active.",
	"An input; a trigger there moves to the next stage.",
	"An input; a trigger there moves to the previous stage.",
	"Sets how many pulses that stage fires, 1 to 8",
};
static const short P112[] = {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10};

/** Sorted by plugin then model, so it can be searched rather than walked. */
const HelpEntry HELP[] = {
	{"Bogaudio", "Bogaudio-AD", L0, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-ADSR", L1, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-AMRM", L2, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-ASR", L3, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Additator", L4, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-AddrSeq", L5, 7, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-AddrSeqX", L6, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Analyzer", L7, 7, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-AnalyzerXL", L8, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Arp", L9, 8, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Assign", L10, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Blank3", L11, 2, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Blank6", L12, 2, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Bool", L13, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-CVD", L14, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Chirp", L15, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Clpr", L16, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Cmp", L17, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-CmpDist", L18, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-DADSRH", L19, 8, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-DADSRHPlus", L20, 2, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-DGate", L21, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Detune", L22, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-EQ", L23, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-EQS", L24, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Edge", L25, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-EightFO", L26, 10, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-EightOne", L27, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-FFB", L28, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-FMOp", L29, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-FlipFlop", L30, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Follow", L31, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-FourFO", L32, 11, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-FourMan", L33, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Inv", L34, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-LFO", L35, 11, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-LLFO", L36, 7, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-LLPG", L37, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-LPG", L38, 7, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-LVCF", L39, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-LVCO", L40, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Lgsw", L41, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Lmtr", L42, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Manual", L43, 2, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Matrix18", L44, 2, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Matrix44", L45, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Matrix44Cvm", L46, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Matrix81", L47, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Matrix88", L48, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Matrix88Cv", L49, 2, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Matrix88M", L50, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-MegaGate", L51, 7, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Mix1", L52, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Mix2", L53, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Mix4", L54, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Mix4x", L55, 7, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Mix8", L56, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Mix8x", L57, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Mono", L58, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Mult", L59, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Mumix", L60, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Mute8", L61, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Noise", L62, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Nsgt", L63, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Offset", L64, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-OneEight", L65, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-PEQ", L66, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-PEQ14", L67, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-PEQ14XF", L68, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-PEQ6", L69, 10, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-PEQ6XF", L70, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Pan", L71, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Pgmr", L72, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-PgmrX", L73, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-PolyCon", L74, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-PolyCon8", L75, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-PolyMult", L76, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-PolyOff16", L77, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-PolyOff8", L78, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Pressor", L79, 8, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Pulse", L80, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-RGate", L81, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Ranalyzer", L82, 10, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Reftone", L83, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-SampleHold", L84, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Shaper", L85, 8, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-ShaperPlus", L86, 2, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Sine", L87, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Slew", L88, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Stack", L89, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Sums", L90, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Switch", L91, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Switch1616", L92, 2, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Switch18", L93, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Switch44", L94, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Switch81", L95, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Switch88", L96, 2, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-UMix", L97, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Unison", L98, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-VCA", L99, 3, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-VCAmp", L100, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-VCF", L101, 7, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-VCM", L102, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-VCO", L103, 13, I103, 4, O103, 4, P103, 7},
	{"Bogaudio", "Bogaudio-VU", L104, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Velo", L105, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Vish", L106, 6, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Walk", L107, 4, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-Walk2", L108, 5, NULL, 0, NULL, 0, NULL, 0},
	{"Bogaudio", "Bogaudio-XCO", L109, 16, I109, 16, O109, 5, P109, 17},
	{"Bogaudio", "Bogaudio-XFade", L110, 4, NULL, 0, NULL, 0, NULL, 0},
	{"NYSTHI", "Model277", L111, 12, I111, 9, O111, 4, P111, 7},
	{"NYSTHI", "Programmer", L112, 11, NULL, 0, NULL, 0, P112, 144},
};
const int HELP_COUNT = 113;
